### ISSUE TITLE
Why go?

### ISSUE THREAD

**Issue by GingerMoon** [neurocult/agency#7]
Hi neurocult,
Thanks for making this interesting project.
I am hesitating which framework to use, a go version or a python version.
Is the only reason why we choose a golang framework because it's more friendly to gophers?
Any insight would be much appreciated!

**Comment by emil14** [comment]
Hi @GingerMoon ! Thank you for having interest to agency :) 

Yes, the main motivation of this library is to create a tool for gophers. As gophers we don't really like the need to use Python. There are many reasons why but they are beyond this question.

So yes, there's only one reason why you should choose agency and that reason is Go.
